### ISSUE TITLE
create a 404 and 500 page for production server

### ISSUE THREAD

**Issue by Lungsangg** [OpenPecha/Pecha.org#411]
# current

The normal 404 page is not showing. debug is still set to True

# Expected

have a user-friendly 404 and 500 page from Django

# New Issue to solve : 

## Description : 
Nginx need to setup in conjunction with python manage.py collectstatic in order to handle static file in production mode so that DEBUG False can work.

- [x] Debug issue
- [x] Setup collectstatic file from django
- [x] Setup Gunicorn
- [x] Setup Nginx 
- [x] Setup Whitenoise
- [x] Test in dev.pecha.org

**Comment by Lungsangg** [comment]
Gen @drupchen la, i have added 404 page and 500 page (for internal server error).

**Comment by drupchen** [comment]
Please tell me where I should test.

I tried in production by removing one letter in the url:

![Image](https://github.com/user-attachments/assets/d716339c-1f85-4f84-a87b-553e74b5208e)

same thing in dev:

![Image](https://github.com/user-attachments/assets/144e0a72-4ba2-4c7d-940e-018b67df0627)

**Comment by Lungsangg** [comment]
![Image](https://github.com/user-attachments/assets/54be71ff-3159-46ae-add2-462c02d34f6b)
@drupchen la its solved, can you plz check in dev

**Comment by Lungsangg** [comment]
@drupchen la, @lobsam  right now couldn't add this to test, as my error solving in render log got stuck at below error/bug
```
Traceback (most recent call last):
info
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 41, in inner
info
    response = get_response(request)
info
  File "/usr/local/lib/python3.7/site-packages/django/utils/deprecation.py", line 140, in __call__
info
    response = self.get_response(request)
info
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 43, in inner
info
    response = response_for_exception(request, exc)
info
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
info
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
info
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 143, in handle_uncaught_exception
info
    return callback(request, **param_dict)
info
  File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
info
    response = view_func(request, *args, **kwargs)
info
  File "/app/reader/views.py", line 4948, in custom_server_error
info
    return render_template(request, template_name=template_name, app_props=None, template_context={}, status=500)
info
  File "/app/reader/views.py", line 185, in render_template
info
    status=status, using=using)
info
  File "/usr/local/lib/python3.7/site-packages/django/shortcuts.py", line 30, in render
info
    content = loader.render_to_string(template_name, context, request, using=using)
info
  File "/usr/local/lib/python3.7/site-packages/django/template/loader.py", line 68, in render_to_string
info
    return template.render(context, request)
info
  File "/usr/local/lib/python3.7/site-packages/django/template/backends/django.py", line 66, in render
info
    return self.template.render(context)
info
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 207, in render
info
    return self._render(context)
info
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 199, in _render
info
    return self.nodelist.render(context)
info
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 990, in render
info
    bit = node.render_annotated(context)
info
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 957, in render_annotated
info
    return self.render(context)
info
  File "/usr/local/lib/python3.7/site-packages/django/template/loader_tags.py", line 177, in render
info
    return compiled_parent._render(context)
info
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 199, in _render
info
    return self.nodelist.render(context)
info
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 990, in render
info
    bit = node.render_annotated(context)
info
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 957, in render_annotated
info
    return self.render(context)
info
  File "/usr/local/lib/python3.7/site-packages/django/template/library.py", line 203, in render
info
    output = self.func(*resolved_args, **resolved_kwargs)
info
  File "/usr/local/lib/python3.7/site-packages/webpack_loader/templatetags/webpack_loader.py", line 22, in render_bundle
info
    attrs=attrs, is_preload=is_preload)
info
  File "/usr/local/lib/python3.7/site-packages/webpack_loader/utils.py", line 63, in get_as_tags
info
    for chunk in bundle:
info
  File "/usr/local/lib/python3.7/site-packages/webpack_loader/loader.py", line 57, in map_chunk_files_to_url
info
    url = self.get_chunk_url(files[chunk])
info
  File "/usr/local/lib/python3.7/site-packages/webpack_loader/loader.py", line 69, in get_chunk_url
info
    return staticfiles_storage.url(relpath)
info
  File "/usr/local/lib/python3.7/site-packages/django/contrib/staticfiles/storage.py", line 162, in url
info
    return self._url(self.stored_name, name, force)
info
  File "/usr/local/lib/python3.7/site-packages/django/contrib/staticfiles/storage.py", line 141, in _url
info
    hashed_name = hashed_name_func(*args)
info
  File "/usr/local/lib/python3.7/site-packages/django/contrib/staticfiles/storage.py", line 432, in stored_name
info
    raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
info
ValueError: Missing staticfiles manifest entry for 'bundles/client/client-3d22b29d0de463207cb9.js'
```

**Comment by drupchen** [comment]
still not showing properly.

ex: https://pecha.org/text
